// src/settlement/settlement.schema.ts
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import mongoose, { Document, Types } from 'mongoose';

export type SettlementDocument = Settlement & Document;

export enum SettlementStatus {
  PENDING = 'pending',
  COMPLETED = 'completed',
  CANCELLED = 'cancelled'
}

@Schema({ timestamps: true })
export class Settlement {
  @Prop({ type: mongoose.Schema.Types.ObjectId, ref: 'Group', required: true })
  groupId: Types.ObjectId;

  @Prop({ type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true })
  fromUserId: Types.ObjectId;

  @Prop({ type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true })
  toUserId: Types.ObjectId;

  @Prop({ type: Number, required: true, min: 0.01 })
  amount: number;

  @Prop({ type: Date, required: true })
  date: Date;

  @Prop({ type: String, enum: SettlementStatus, default: SettlementStatus.PENDING })
  status: SettlementStatus;

  @Prop()
  description: string;

  // Metadata
  @Prop({ type: Boolean, default: false })
  isAutoGenerated: boolean;

  @Prop()
  paymentMethod: string;

  @Prop()
  transactionId: string;

  createdAt: Date;
  updatedAt: Date;
}

export const SettlementSchema = SchemaFactory.createForClass(Settlement);

// Create indexes
SettlementSchema.index({ groupId: 1, status: 1 });
SettlementSchema.index({ groupId: 1, fromUserId: 1, toUserId: 1 });
SettlementSchema.index({ groupId: 1, date: -1 });