// src/settlement/settlement.type.ts
export enum SettlementStatus {
  PENDING = 'pending',
  COMPLETED = 'completed',
  CANCELLED = 'cancelled'
}

export interface Balance {
  userId: string;
  userName: string;
  amount: number; // Positive = owed to user, Negative = owes
  paidAmount: number;
  owedAmount: number;
}

export interface SettlementOptimizationResult {
  fromUserId: string;
  fromUserName: string;
  toUserId: string;
  toUserName: string;
  amount: number;
}

export interface CreateSettlementDto {
  fromUserId: string;
  toUserId: string;
  amount: number;
  date: Date;
  description?: string;
}

export interface SettlementResponse {
  id: string;
  groupId: string;
  fromUserId: string;
  fromUserName: string;
  toUserId: string;
  toUserName: string;
  amount: number;
  date: Date;
  status: string;
  description?: string;
  paymentMethod?: string;
  transactionId?: string;
  isAutoGenerated: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface SettlementStatistics {
  totalSettlements: number;
  totalAmount: number;
  totalDebt: number;
  pendingCount: number;
  completedCount: number;
  cancelledCount: number;
  recentSettlements: SettlementResponse[];
  balances: Balance[];
}