// src/settlement/settlement.dto.ts - FINAL CORRECTED VERSION
import {
  IsMongoId,
  IsNumber,
  IsDate,
  IsOptional,
  IsString,
  IsEnum,
  Min,
  MaxLength,
  IsBoolean,
  IsNotEmpty,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { SettlementStatus } from './settlement.schema';

// Request DTOs
export class CreateSettlementDto {
  @ApiProperty({
    example: '507f1f77bcf86cd799439011',
    description: 'User who owes money (payer)',
  })
  @IsMongoId()
  @IsNotEmpty()
  fromUserId: string;

  @ApiProperty({
    example: '507f1f77bcf86cd799439012',
    description: 'User who is owed money (receiver)',
  })
  @IsMongoId()
  @IsNotEmpty()
  toUserId: string;

  @ApiProperty({
    example: 1500.5,
    description: 'Settlement amount',
    minimum: 0.01,
  })
  @IsNumber()
  @Min(0.01, { message: 'Amount must be greater than 0' })
  amount: number;

  @ApiProperty({
    example: '2024-01-15T10:30:00.000Z',
    description: 'Settlement date',
  })
  @IsDate()
  @Type(() => Date)
  date: Date;

  @ApiPropertyOptional({
    example: 'Dinner expense settlement',
    description: 'Settlement description',
    maxLength: 500,
  })
  @IsOptional()
  @IsString()
  @MaxLength(500)
  description?: string;

  @ApiPropertyOptional({
    example: 'UPI',
    description: 'Payment method used',
    enum: [
      'UPI',
      'CASH',
      'BANK_TRANSFER',
      'CREDIT_CARD',
      'DEBIT_CARD',
      'PAYTM',
      'PHONEPE',
      'GOOGLE_PAY',
    ],
  })
  @IsOptional()
  @IsString()
  paymentMethod?: string;

  @ApiPropertyOptional({
    example: 'TXN123456789',
    description: 'Transaction ID for reference',
  })
  @IsOptional()
  @IsString()
  @MaxLength(100)
  transactionId?: string;

  @ApiPropertyOptional({
    example: false,
    description: 'Whether settlement was auto-generated',
  })
  @IsOptional()
  @IsBoolean()
  isAutoGenerated?: boolean = false;
}

export class UpdateSettlementStatusDto {
  @ApiProperty({
    example: 'completed',
    description: 'New settlement status',
    enum: Object.values(SettlementStatus),
  })
  @IsEnum(SettlementStatus)
  status: SettlementStatus;
}

export class GetSettlementsQueryDto {
  @ApiPropertyOptional({
    example: 'pending',
    description: 'Filter by status',
    enum: Object.values(SettlementStatus),
  })
  @IsOptional()
  @IsEnum(SettlementStatus)
  status?: SettlementStatus;

  @ApiPropertyOptional({
    example: '2024-01-01',
    description: 'Filter from date',
  })
  @IsOptional()
  @IsDate()
  @Type(() => Date)
  fromDate?: Date;

  @ApiPropertyOptional({
    example: '2024-12-31',
    description: 'Filter to date',
  })
  @IsOptional()
  @IsDate()
  @Type(() => Date)
  toDate?: Date;

  @ApiPropertyOptional({
    example: '507f1f77bcf86cd799439011',
    description: 'Filter by user ID',
  })
  @IsOptional()
  @IsMongoId()
  userId?: string;

  @ApiPropertyOptional({
    example: true,
    description: 'Filter by auto-generated settlements',
  })
  @IsOptional()
  @IsBoolean()
  isAutoGenerated?: boolean;

  @ApiPropertyOptional({
    example: 'date',
    description: 'Sort by field',
    enum: ['date', 'amount', 'createdAt', 'updatedAt'],
  })
  @IsOptional()
  @IsEnum(['date', 'amount', 'createdAt', 'updatedAt'])
  sortBy?: string = 'date';

  @ApiPropertyOptional({
    example: 'desc',
    description: 'Sort order',
    enum: ['asc', 'desc'],
  })
  @IsOptional()
  @IsEnum(['asc', 'desc'])
  sortOrder?: string = 'desc';

  @ApiPropertyOptional({
    example: 1,
    description: 'Page number',
    minimum: 1,
  })
  @IsOptional()
  @Type(() => Number)
  page?: number = 1;

  @ApiPropertyOptional({
    example: 20,
    description: 'Items per page',
    minimum: 1,
    maximum: 100,
  })
  @IsOptional()
  @Type(() => Number)
  limit?: number = 20;
}

export class CreateOptimizedSettlementsDto {
  @ApiProperty({
    example: true,
    description: 'Automatically create optimized settlements',
  })
  @IsBoolean()
  autoCreate: boolean = true;

  @ApiPropertyOptional({
    example: 5,
    description: 'Maximum number of settlements to create',
    minimum: 1,
  })
  @IsOptional()
  @IsNumber()
  @Min(1)
  maxSettlements?: number;
}

// Response DTOs
export class SettlementResponseDto {
  @ApiProperty({
    example: '507f1f77bcf86cd799439011',
    description: 'Settlement ID',
  })
  id: string;

  @ApiProperty({ example: '507f1f77bcf86cd799439021', description: 'Group ID' })
  groupId: string;

  @ApiProperty({
    example: '507f1f77bcf86cd799439011',
    description: 'User who owes money (payer)',
  })
  fromUserId: string;

  @ApiProperty({
    example: 'John Doe',
    description: 'Payer user name',
  })
  fromUserName: string;

  @ApiProperty({
    example: '507f1f77bcf86cd799439012',
    description: 'User who is owed money (receiver)',
  })
  toUserId: string;

  @ApiProperty({
    example: 'Jane Smith',
    description: 'Receiver user name',
  })
  toUserName: string;

  @ApiProperty({ example: 1500.5, description: 'Settlement amount' })
  amount: number;

  @ApiProperty({
    example: '2024-01-15T10:30:00.000Z',
    description: 'Settlement date',
  })
  date: Date;

  @ApiProperty({
    example: 'pending',
    description: 'Settlement status',
    enum: Object.values(SettlementStatus),
  })
  status: SettlementStatus;

  @ApiPropertyOptional({
    example: 'Dinner expense settlement',
    description: 'Settlement description',
  })
  description?: string;

  @ApiPropertyOptional({
    example: 'UPI',
    description: 'Payment method used',
  })
  paymentMethod?: string;

  @ApiPropertyOptional({
    example: 'TXN123456789',
    description: 'Transaction ID',
  })
  transactionId?: string;

  @ApiProperty({
    example: false,
    description: 'Whether settlement was auto-generated',
  })
  isAutoGenerated: boolean;

  @ApiProperty({
    example: '2024-01-15T10:30:00.000Z',
    description: 'Creation date',
  })
  createdAt: Date;

  @ApiProperty({
    example: '2024-01-15T10:30:00.000Z',
    description: 'Last update date',
  })
  updatedAt: Date;
}

export class BalanceResponseDto {
  @ApiProperty({
    example: '507f1f77bcf86cd799439011',
    description: 'User ID',
  })
  userId: string;

  @ApiProperty({
    example: 'John Doe',
    description: 'User name',
  })
  userName: string;

  @ApiProperty({
    example: -1500.5,
    description: 'Net balance (negative = owes, positive = is owed)',
  })
  amount: number;

  @ApiProperty({
    example: 5000,
    description: 'Total amount paid by user',
  })
  paidAmount: number;

  @ApiProperty({
    example: 3500,
    description: 'Total amount owed by user',
  })
  owedAmount: number;

  @ApiProperty({
    example: 'INR',
    description: 'Currency',
  })
  currency: string;
}

export class SettlementOptimizationResultDto {
  @ApiProperty({
    example: '507f1f77bcf86cd799439011',
    description: 'Payer user ID',
  })
  fromUserId: string;

  @ApiProperty({
    example: 'John Doe',
    description: 'Payer user name',
  })
  fromUserName: string;

  @ApiProperty({
    example: '507f1f77bcf86cd799439012',
    description: 'Receiver user ID',
  })
  toUserId: string;

  @ApiProperty({
    example: 'Jane Smith',
    description: 'Receiver user name',
  })
  toUserName: string;

  @ApiProperty({
    example: 1500.5,
    description: 'Settlement amount',
  })
  amount: number;
}

export class SettlementStatisticsDto {
  @ApiProperty({
    example: 25,
    description: 'Total number of settlements',
  })
  totalSettlements: number;

  @ApiProperty({
    example: 50000.75,
    description: 'Total amount settled',
  })
  totalAmount: number;

  @ApiProperty({
    example: 10000.25,
    description: 'Total outstanding debt',
  })
  totalDebt: number;

  @ApiProperty({
    example: 5,
    description: 'Number of pending settlements',
  })
  pendingCount: number;

  @ApiProperty({
    example: 18,
    description: 'Number of completed settlements',
  })
  completedCount: number;

  @ApiProperty({
    example: 2,
    description: 'Number of cancelled settlements',
  })
  cancelledCount: number;

  @ApiProperty({
    description: 'Recent settlements',
    type: [SettlementResponseDto],
  })
  recentSettlements: SettlementResponseDto[];

  @ApiProperty({
    description: 'Current balances',
    type: [BalanceResponseDto],
  })
  balances: BalanceResponseDto[];
}

export class SettlementListResponseDto {
  @ApiProperty({
    description: 'List of settlements',
    type: [SettlementResponseDto],
  })
  settlements: SettlementResponseDto[];

  @ApiProperty({
    example: 25,
    description: 'Total number of settlements',
  })
  total: number;

  @ApiProperty({
    example: 1,
    description: 'Current page number',
  })
  page: number;

  @ApiProperty({
    example: 20,
    description: 'Items per page',
  })
  limit: number;

  @ApiProperty({
    example: 2,
    description: 'Total number of pages',
  })
  totalPages: number;
}
