// src/settlement/settlement.domain.ts
export interface SettlementSplit {
  userId: string;
  amount: number;
  note?: string;
}

export class SettlementDomain {
  constructor(
    public readonly id: string,
    public readonly groupId: string,
    public readonly fromUserId: string,
    public readonly toUserId: string,
    public readonly amount: number,
    public readonly date: Date,
    public readonly status: string,
    public readonly description?: string,
    public readonly paymentMethod?: string,
    public readonly transactionId?: string,
    public readonly isAutoGenerated: boolean = false,
    public readonly createdAt?: Date,
    public readonly updatedAt?: Date,
  ) {}

  static create(
    groupId: string,
    fromUserId: string,
    toUserId: string,
    amount: number,
    date: Date,
    status: string,
    description?: string,
    paymentMethod?: string,
    transactionId?: string,
    isAutoGenerated: boolean = false,
  ): SettlementDomain {
    return new SettlementDomain(
      '',
      groupId,
      fromUserId,
      toUserId,
      amount,
      date,
      status,
      description,
      paymentMethod,
      transactionId,
      isAutoGenerated,
    );
  }

  updateStatus(status: string): SettlementDomain {
    return new SettlementDomain(
      this.id,
      this.groupId,
      this.fromUserId,
      this.toUserId,
      this.amount,
      this.date,
      status,
      this.description,
      this.paymentMethod,
      this.transactionId,
      this.isAutoGenerated,
      this.createdAt,
      this.updatedAt,
    );
  }
}