// src/shared/database/mapper/settlement.mapper.ts
import { Types } from 'mongoose';
import { Settlement, SettlementDocument, SettlementStatus } from '../../../settlement/settlement.schema';
import { SettlementDomain } from '../../../settlement/settlement.domain';

export class SettlementMapper {
  static toDomain(settlement: SettlementDocument): SettlementDomain | null {
    if (!settlement) return null;

    return new SettlementDomain(
      settlement._id.toString(),
      settlement.groupId.toString(),
      settlement.fromUserId.toString(),
      settlement.toUserId.toString(),
      settlement.amount,
      settlement.date,
      settlement.status,
      settlement.description,
      settlement.paymentMethod,
      settlement.transactionId,
      settlement.isAutoGenerated || false,
      settlement.createdAt,
      settlement.updatedAt,
    );
  }

  static toEntity(domain: SettlementDomain): Partial<Settlement> {
    return {
      groupId: new Types.ObjectId(domain.groupId),
      fromUserId: new Types.ObjectId(domain.fromUserId),
      toUserId: new Types.ObjectId(domain.toUserId),
      amount: domain.amount,
      date: domain.date,
      status: domain.status as SettlementStatus,
      description: domain.description,
      paymentMethod: domain.paymentMethod,
      transactionId: domain.transactionId,
      isAutoGenerated: domain.isAutoGenerated,
    };
  }
}